modify exception
alibaba/easyexcel pull request #1534
Opened 2020-08-24 07:23 UTC by Alanscut

2020-08-24 07:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/easyexcel?pullRequest=1534) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/easyexcel?pullRequest=1534) before we can accept your contribution.<br/><hr/>**Mr14huashao** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/easyexcel?pullRequest=1534) it.</sub>

2020-10-26 12:06 UTC, Bennyhwanggggg requested changes

2020-10-26 12:06 UTC, Bennyhwanggggg commented on src/main/java/com/alibaba/excel/write/metadata/holder/WriteWorkbookHolder.java
> +            throw new IOException(e.getMessage(), e);
why not just throw this as a general exception after ExcelGenerateException? Catching the same exception and throwing it seems pointless here.

2021-04-09 03:42 UTC, zhuangjiaju commented
非常感谢您的PR.
但是目前没有抛出 `IOException `的情况。暂时先不合并 ，感谢。

2021-04-09 03:42 UTC, closed without merging